src/Entity/Question.php
<?php

namespace App\Entity;

use App\Repository\QuestionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=QuestionRepository::class)
 */
class Question
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $question;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titre;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="questions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    /**
     * @ORM\OneToMany(targetEntity=Comments::class, mappedBy="Question")
     */
    private $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuestion(): ?string
    {
        return $this->question;
    }

    public function setQuestion(?string $question): self
    {
        $this->question = $question;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setQuestion($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getQuestion() === $this) {
                $comment->setQuestion(null);
            }
        }

        return $this;
    }
}

src/Form/QuestionType.php
<?php

namespace App\Form;

use App\Entity\Question;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class QuestionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Titre',TextType::class)
            ->add('question',TextAreaType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Question::class,
        ]);
    }
}

src/Controller/QuestionController.php
<?php

namespace App\Controller;

use App\Entity\Comments;
use App\Entity\Question;
use App\Entity\User;
use App\Form\QuestionType;
use App\Repository\UserRepository;
use App\Repository\CommentsRepository;
use App\Repository\QuestionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class QuestionController extends AbstractController
{
    /**
     * @Route("/ViewQuests", name="ViewQuests")
     * IsGranted("ROLE_USER")
     */
    public function index(QuestionRepository $QR,CommentsRepository $CR): Response{
        $user=$this->getUser();
        $cmnts=$CR->findAll();
        $quests=$QR->findAll();
        return $this->render('question/view.html.twig', [
            "quests"=>$quests,"comment"=>$cmnts,"user"=>$user
        ]);
    }
    /**
     * @Route("/ViewDetails", name="ViewDetails")
     * IsGranted("ROLE_USER")
     */
    public function ViewDetails(Request $request,QuestionRepository $QR,CommentsRepository $CR): Response{
        $user=$this->getUser();
        $quest=$QR->find($request->query->get('quest'));
        $cmnts=$CR->findBy(['Question'=>$quest]);
        return $this->render('question/viewComments.html.twig', [
            "quest"=>$quest,"comment"=>$cmnts,"user"=>$user
        ]);
    }
    /**
     * @Route("/deltequest", name="deltequest")
     * IsGranted("ROLE_USER")
     */
    public function deltequest(Request $request,CommentsRepository $CR,QuestionRepository $QR,EntityManagerInterface $manager): Response {
      $quest=$QR->find($request->query->get('quest'));
      $manager->remove($quest);
        $manager->flush();
        return $this->redirect("/ViewQuests");
    }
    /**
     * @Route("/Comment", name="Comment")
     * IsGranted("ROLE_USER")
     */
    public function addComment(Request $request,CommentsRepository $CR,QuestionRepository $QR,EntityManagerInterface $manager): Response {
        $comment= new Comments();
        $quest= new Question();
        $comment->setUser($this->getUser());
        $quest=$QR->find($request->query->get('quest'));
        $comment->setComment($request->query->get('comment'));
        $comment->setQuestion($quest);
        $manager->persist($comment);
        $manager->flush();
        $user=$this->getUser();
        $cmnts=$CR->findBy(['Question'=>$quest]);
        return $this->render('question/viewComments.html.twig', [
            "quest"=>$quest,"comment"=>$cmnts,"user"=>$user
        ]);
    }
    /**
     * @Route("/deletecmnt", name="deletecmnt")
     * IsGranted("ROLE_USER")
     */
    public function deleteComment(Request $request,CommentsRepository $CR,EntityManagerInterface $manager):Response{
        $comment= $CR->find($request->query->get('idcmnt'));
        $manager->remove($comment);
        $manager->flush();
        return $this->redirect("/ViewQuests");
    }

    /**
     * @Route("/createpost", name="createpost")
     * IsGranted("ROLE_USER")
     */
    public function create(Request $request,EntityManagerInterface $manager): Response
    {
        $question= new Question();
        $formquest=$this->createForm(QuestionType:: class,$question);
        $formquest->handleRequest($request);
        if($formquest->isSubmitted() and $formquest->isValid()){

            $question->setUser($this->getUser());
            $manager->persist($question);
            $manager->flush();
            return $this->redirect("/ViewQuests");
        }
        return $this->render('question/index.html.twig', [
            "formquest"=>$formquest->createView(),
        ]);
    }
}

templates/question/View.html.twig
{% extends 'base.html.twig' %}

{% block title %}Login!{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="style.css">
{% endblock %}
{% block javascripts %}
{% endblock %}
{% block body %}
<div class="container">
<a href="{{path('logout')}}">logout</a>
<a href="{{path('createpost')}}">Add a new post</a>

{% for quest in quests %}
    <hr>
    <div>
        <div><b>{{quest.titre}}</b></div>
        <div>{{quest.question}}</div>
        <div class="small">{{quest.user.email}}</div>
    </div>
    <div>
        <form action="{{path('ViewDetails')}}" action="post">
            <input type="Hidden" name="quest" id="quest" value="{{quest.id}}">
            <label for="comment">More details:</label>
            <button type="submit">View discussion</button>
        </form>
    </div>
    
{% endfor %}
</div>
{% endblock %}

templates/question/ViewComments.html.twig
{% extends 'base.html.twig' %}

{% block title %}Login!{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="style.css">
{% endblock %}
{% block javascripts %}
{% endblock %}
{% block body %}
<div class="container">

<a href="{{path('logout')}}">logout</a>
<a href="{{path('ViewQuests')}}">go back</a>
<hr>
    <div>
    <form action="{{path('deltequest')}}" action="post">
        <div><b>{{quest.titre}}</b></div>
        <div>{{quest.question}}</div>
        <div>{{quest.user.email}}</div>
            <input type="Hidden" name="quest" id="quest" value="{{quest.id}}">
            {% if quest.user == user %}
        <button type="submit">Delete</button>
        {% endif %}
    </form>
    </div>
    <div>
        <form action="{{path('Comment')}}" action="post">
            <input type="Hidden" name="user" id="user" value="{{quest.user.id}}">
            <input type="Hidden" name="quest" id="quest" value="{{quest.id}}">
            <label for="comment">add a new comment:</label>
            <input type="text" name="comment" id="comment" required>
            <button type="submit">Send</button>
        </form>
    </div>
    
    {% for cmnt in comment %}
    <hr>
        {% if cmnt.question == quest %}
        {% if cmnt.user == user  %}
        <form action="{{path('deletecmnt')}}">
            <div>
            &nbsp;&nbsp;<b> {{cmnt.user.email}}</b>
            </div>
            <div> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{cmnt.comment}} </div>
            <input type="hidden" name="idcmnt" id="idcmnt" value="{{cmnt.id}}">
            <button type="submit">delete</button>
        </form>
        {% else %}
            <div>
            &nbsp;&nbsp;<b> {{cmnt.user.email}}</b>
            </div>
            <div> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{cmnt.comment}} </div>
            <input type="hidden" name="idcmnt" id="idcmnt">
        {% endif %}
        {% endif %}
{% endfor %}
</div>
{% endblock %}

templates/question/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Post a Question!{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="style.css">

{% endblock %}
{% block javascripts %}
{% endblock %}
{% block body %}
<div class="center">
<h1>New post</h1>
    {{form_start(formquest)}}
            <div class="txt">
                {{form_row(formquest.Titre)}}
            </div>
            <div class="txt">
                {{form_row(formquest.question,{ 'label': 'Description' })}}
            </div>
            <div class="txt">
                    <input type="submit" value="Register">
            </div>
            <div class="my-custom-class-for-errors">
                {{form_errors(formquest)}}
            </div>
    {{form_end(formquest)}}
    </div>
{% endblock %}